---
apiVersion: v1
kind: Namespace
metadata:
  name: @@app@@
---
apiVersion: v1
kind: Service
metadata:
  name: @@app@@
  namespace: @@namespace@@
spec:
  selector:
    app: @@app@@
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: @@service_port@@
      targetPort: @@container_port@@
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: @@app@@
  namespace: @@namespace@@
spec:
  selector:
    matchLabels:
      app: @@app@@ # has to match .spec.template.metadata.labels
  serviceName: @@app@@
  replicas: 1
  template:
    metadata:
      labels:
        app: @@app@@ # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: @@app@@
          image: @@image@@
          imagePullPolicy: Always
          ports:
            - containerPort: @@container_port@@
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
  volumeClaimTemplates:
    - metadata:
        name: config
        namespace: @@namespace@@
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi